formatter: "markdown table"
content: |-
  ## Example

  ```hcl
  {{ include "main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
