name: Publishing new version on pushes to master.

on:
  push:
    branches:
      - master
jobs:
  validate:
    name: Publish module
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}